server:
  port: 8686
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
      max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare-threads: 30
    #自定义管理端点可用的地址。
  #address: localhost
#  server.ssl.enabled=true
#  server.ssl.key-store=classpath:main.jks
#  server.ssl.key-password=secret
#终端CORS配置（EndpointCorsProperties）
spring:
  datasource:
    #配置hikari连接池
    hikari:
      #最小空闲连接数量
      minimum-idle: 4
      # 连接池最大连接数，默认是10
      maximum-pool-size: 16
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 10000
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      #connection-init-sql: set names utf8mb4
      connection-test-query: SELECT 1
    #动态数据源配置
    dynamic:
      #主数据源
      primary: a01
      datasource:
        #数据源a01
        a01:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ip:3306/kevinBoot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: kevinBoot
          password: EiC7f6FdXxDmXd2j
        #数据源a03
        a03:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://ip:3306/worker?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
          username: scheduledb
          password: XSLstbx7iXBXNzeR
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
#redis配置
  redis:
    host: 120.92.154.4
    port: 8808
    timeout: 10000
    database: 0
    password: wTTXaRYSThTNeeGL
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #配置不给前端返回null
    default-property-inclusion: non_null
  devtools:
    restart:
      enabled: true

#分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

  # mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mapperxml/*.xml
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
logging:
  config: classpath:logback-spring.xml

# 代码生成
gen:
  # 作者
  author: kevin
  # 默认生成包路径 module 需改成自己的模块名称 如 com kevin system
  packageName: com.kevin.system
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀(类名不会包含表前缀)
  tablePrefix:
xss:
  enabled: true
  excludes:
  includes:
  encoding: UTF-8
  url-patterns: /common/*,/resources/*,/monitor/*,/system/*
